version: "3.7"
services:
  app:
    build:
      args:
        user: me
        uid: 1000
      context: ..
      dockerfile: docker/Dockerfile
    container_name: parser-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ..:/var/www
    networks:
      - parser-app
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: parser-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=rss-parser
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USERNAME=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    ports:
      - 3306:3306
    volumes:
      - ../docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - parser-app
  nginx:
    image: nginx:1.17-alpine
    container_name: parser-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ..:/var/www
      - ../docker/nginx:/etc/nginx/conf.d
    networks:
      - parser-app
networks:
  parser-app:
    driver: bridge
